source 'https://rubygems.org'

gem 'rails', '4.0.8'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'ruby_spark'
gem 'pry'
gem 'rails_12factor'
gem 'pg'
gem 'lockup'
